import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Card, ErrorBox, Loading, TimeCell, Confirm } from '../components/ui';
import { GSelect } from '../components/GSelect';
import Markdown from '../components/Markdown';
import { Head, LoginLink, request, SignedIn, stamp, useAction, useAuth, usePager, User } from './core';

const kindNames: Record<string, string> = { watch: '关注的 Issue 评论或标签变化', opportunity: '新的可参与 Issue', taken: 'Issue 被认领', resolved: 'Issue 标记完成', closed: 'Issue 关闭', reopened: '机会重新开放', release: '新版本', tripwire: '功能判断变化', breaking: '破坏性变更', cve: '依赖漏洞' };
export function Settings() {
  const auth = useAuth();
  return <><Head title="设置" help={<><p>登录只使用 GitHub。我们读取公开信息，不修改 GitHub 的 Star、Issue、PR 或通知。</p><p>邮件由 Gitwire 独立发送，需要验证你填写的收件邮箱；验证本身不会开启提醒。免打扰起止时间相同时表示全天允许发送。</p><p>退出登录只退出浏览器会话，服务器继续监控。断开 GitHub 会停止需要该授权的同步；暂停监控请到监控清单操作。</p></>} /><Card title="GitHub 账户">{auth.user ? <div className="host-row"><strong>{auth.user.login}</strong><span className="badge">{auth.user.reconnect_required ? '需要重新连接' : '已连接 · 只读'}</span>{auth.user.reconnect_required && <LoginLink />}</div> : <><p>访客可以查询公开项目。登录后保存关注，并让服务器持续跟进。</p><LoginLink /></>}</Card>{auth.user && <Preferences key={auth.user.id} user={auth.user} />}</>;
}
function Preferences({ user }: { user: User }) {
  const [prefs, setPrefs] = useState(user), [email, setEmail] = useState(user.email), [disconnect, setDisconnect] = useState(false);
  const verifyToken = new URLSearchParams(window.location.search).get('verify');
  const save = useAction((snapshot: User) => request('/preferences', 'PATCH', { timezone: snapshot.timezone, digest_hour: snapshot.digest_hour, email_enabled: snapshot.email_enabled, email_mode: snapshot.email_mode, quiet_start: snapshot.quiet_start, quiet_end: snapshot.quiet_end, notify_kinds: snapshot.notify_kinds }));
  const send = useAction(() => request('/email/verify-request', 'POST', { email }));
  const verify = useAction(async () => { const r = await request('/email/verify', 'POST', { token: verifyToken }); window.history.replaceState({}, '', '/settings'); return r; });
  const unlink = useAction(async () => { await request('/auth/disconnect', 'POST'); setDisconnect(false); });
  const logout = useAction(async () => { await request('/auth/logout', 'POST'); window.location.replace('/issues?auth=logged-out'); });
  return <div className="host-settings">
    {verifyToken && <Card title="确认收件邮箱"><p>确认此邮箱用于接收你的 Gitwire 提醒。</p><button className="btn" disabled={verify.isPending} onClick={() => verify.mutate(null)}>验证邮箱</button>{verify.error && <ErrorBox error={verify.error} />}{verify.isSuccess && <p role="status">邮箱已验证。你可以开启提醒。</p>}</Card>}
    <Card title="邮件提醒"><p><Link className="btn ghost" to="/deliveries">查看邮件投递记录</Link></p><form onSubmit={e => { e.preventDefault(); send.mutate(null); }}><label className="host-field">收件邮箱<div className="host-row"><input className="input" type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" required /><button className="btn ghost" disabled={send.isPending}>发送验证邮件</button></div></label><p className="small">{user.email_verified ? '已验证：' + user.email : '尚未验证邮箱'}</p></form>{send.error && <ErrorBox error={send.error} />}{send.isSuccess && <p role="status">验证邮件已加入发送队列，请检查收件箱。</p>}
    <label className="host-check"><input type="checkbox" checked={prefs.email_enabled} disabled={!user.email_verified} onChange={e => setPrefs({ ...prefs, email_enabled: e.target.checked })} />开启邮件提醒</label>{!user.email_verified && <p className="dim small">先验证收件邮箱，再开启邮件提醒。</p>}
    <label className="host-field">发送方式<GSelect value={prefs.email_mode} onChange={v => setPrefs({ ...prefs, email_mode: v })} options={[{ value: 'digest', label: '仅每日汇总' }, { value: 'immediate', label: '变化后提醒' }, { value: 'both', label: '变化提醒与每日汇总' }]} /></label>
    <fieldset><legend>我关心的变化</legend>{Object.entries(kindNames).map(([key, label]) => <label key={key} className="host-check"><input type="checkbox" checked={prefs.notify_kinds.includes(key)} onChange={e => setPrefs({ ...prefs, notify_kinds: e.target.checked ? [...prefs.notify_kinds, key] : prefs.notify_kinds.filter(v => v !== key) })} />{label}</label>)}</fieldset>
    </Card>
    <Card title="时间偏好"><label className="host-field">时区<GSelect value={prefs.timezone} onChange={v => setPrefs({ ...prefs, timezone: v })} options={[{ value: 'Asia/Shanghai', label: '中国标准时间' }, { value: 'UTC', label: 'UTC' }, { value: 'America/New_York', label: '纽约' }, { value: 'Europe/London', label: '伦敦' }, { value: 'Asia/Tokyo', label: '东京' }]} /></label><div className="host-form-grid">{([{ key: 'digest_hour', label: '每日汇总时间' }, { key: 'quiet_start', label: '免打扰开始' }, { key: 'quiet_end', label: '免打扰结束' }] as const).map(x => <label className="host-field" key={x.key}>{x.label}<GSelect value={String(prefs[x.key])} onChange={v => setPrefs({ ...prefs, [x.key]: Number(v) })} options={Array.from({ length: 24 }, (_, i) => ({ value: String(i), label: `${String(i).padStart(2, '0')}:00` }))} /></label>)}</div></Card><div className="host-savebar"><span>邮件提醒与时间偏好需保存后生效</span><button className="btn" disabled={save.isPending} onClick={() => save.mutate(prefs)}>{save.isPending ? '正在保存…' : '保存提醒设置'}</button>{save.error && <ErrorBox error={save.error} />}{save.isSuccess && JSON.stringify(prefs) === JSON.stringify(save.variables) && <span role="status">设置已保存。</span>}</div>
    <Card title="成果保存"><p>分析结果和历史版本保存在服务器。你可以下载自己的情报，保存到本地并用本机 Git 备份。</p><div className="host-row"><a className="btn ghost" href="/api/export">下载我的情报</a><Link className="btn ghost" to="/legacy">旧版私人资料</Link></div><p className="dim small">GitHub 远程备份由本地工具使用你已有的 Git 凭证完成，不使用登录 Token。</p></Card>
    <Card title="会话与连接"><div className="host-row"><button className="btn ghost" disabled={logout.isPending} onClick={() => logout.mutate(null)}>{logout.isPending ? '正在退出…' : '退出登录'}</button><button className="btn ghost" onClick={() => setDisconnect(true)}>断开 GitHub 连接</button></div>{(logout.error || unlink.error) && <ErrorBox error={logout.error || unlink.error} />}</Card>
    <Confirm open={disconnect} title="断开 GitHub 连接" body="删除 Gitwire 保存的 GitHub 授权，停止 Star 等账户同步。已有情报会保留；若要停止公开仓库监控，请在监控清单中暂停。" onConfirm={() => unlink.mutate(null)} onClose={() => setDisconnect(false)} />
  </div>;
}

export function PersonalList({ kind }: { kind: 'jobs' | 'notifications' | 'daily' }) {
  const auth = useAuth(), pg = usePager();
  const titles = { jobs: '运行历史', notifications: '警报', daily: '每日晨报' };
  const query = useQuery({ queryKey: [kind, auth.user?.id, pg.page, pg.size], queryFn: () => request(`/${kind}?${pg.query}`), enabled: !!auth.user, refetchInterval: 10000 });
  const read = useAction((id: string) => request(`/notifications/${id}/read`, 'POST'));
  return <><Head title={titles[kind]} help={<><p>这里只显示与你的账户相关的内容。任务在服务器执行，关闭页面不影响运行。</p>{kind === 'jobs' ? <p>等待中表示任务尚未执行；重试会显示尝试次数。失败后保留记录，不会把失败结果当作完成。</p> : kind === 'notifications' ? <p>警报来自你选择的监控与规则。“已标记完成”依据 GitHub Issue 状态；“已关闭”不一定代表问题被解决。这里的已读状态不会影响 GitHub。</p> : <p>晨报按你设置的时区生成，先检查 Star，再汇总上次晨报以来尚未汇总的关注动态和候选。停机期间和延迟到达的记录会补入；候选不会自动加入监控。</p>}</>} /><SignedIn>{(query.error || read.error) && <ErrorBox error={query.error || read.error} />}<Card>{query.isPending ? <Loading /> : query.isError && !query.data ? <button className="btn ghost" onClick={() => query.refetch()}>重新加载</button> : !query.data?.items.length ? <div className="host-empty"><h2>{kind === 'daily' ? '还没有晨报' : kind === 'jobs' ? '暂无运行记录' : '暂无警报'}</h2><p>{kind === 'daily' ? '添加监控后，系统会按你的时间偏好汇总项目动态。' : '项目出现符合提醒规则的变化后，会显示在这里。'}</p><Link className="btn ghost" to="/repos">前往监控清单</Link></div> : kind === 'daily' ? query.data.items.map((d: any) => <article className="host-digest" key={d.id}><Markdown text={d.content} /></article>) : <div className="host-table-wrap"><table className="tbl"><thead><tr><th>{kind === 'jobs' ? '任务' : '内容'}</th><th>状态</th><th>时间</th></tr></thead><tbody>{query.data.items.map((r: any) => <tr key={r.id}><td>{kind === 'jobs' ? <><strong>{{ scan: '更新仓库动态', candidates: '同步候选仓库', analyze_issue: '分析 Issue', analyze_repo: '更新项目档案', digest: '生成晨报' }[r.kind as string] || r.kind}</strong><p className="small">{r.error || (r.result?.count !== undefined ? `已处理 ${r.result.count} 项` : '')}</p></> : <><a href={r.url} target="_blank" rel="noreferrer">{r.title}</a><p className="small">{r.body}</p><span className="dim small">{r.repo}</span></>}</td><td className="nw">{kind === 'jobs' ? <>{({ pending: '等待中', running: '运行中', completed: '已完成', failed: '失败' } as Record<string, string>)[r.status]}<div className="small">已尝试 {r.attempts} 次</div></> : r.read_at ? '已读' : <button className="btn ghost" onClick={() => read.mutate(r.id)}>标为已读</button>}</td><td><TimeCell iso={stamp(r.created_at)} /></td></tr>)}</tbody></table></div>}{pg.view(query.data)}</Card></SignedIn></>;
}
