"""Frozen initial hosted schema: public corpus, accounts, jobs and outbox."""
from alembic import op
import sqlalchemy as sa

revision = '0001_hosted'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('h_account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('github_id', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('token_expires', sa.Integer(), nullable=False),
    sa.Column('reconnect_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('digest_hour', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_mode', sa.String(), nullable=False),
    sa.Column('quiet_start', sa.Integer(), nullable=False),
    sa.Column('quiet_end', sa.Integer(), nullable=False),
    sa.Column('notify_kinds', sa.JSON(), nullable=False),
    sa.Column('stars_synced_at', sa.Integer(), nullable=False),
    sa.Column('digest_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_h_account_github_id'), 'h_account', ['github_id'], unique=True)
    op.create_table('h_http_cache',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('etag', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('h_oauth_attempt',
    sa.Column('digest', sa.String(), nullable=False),
    sa.Column('browser_digest', sa.String(), nullable=False),
    sa.Column('verifier', sa.String(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('digest')
    )
    op.create_table('h_quota',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_h_quota_expires_at'), 'h_quota', ['expires_at'], unique=False)
    op.create_table('h_repository',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('github_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.Integer(), nullable=False),
    sa.Column('next_scan', sa.Integer(), nullable=False),
    sa.Column('unavailable_reason', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_h_repository_full_name'), 'h_repository', ['full_name'], unique=True)
    op.create_index(op.f('ix_h_repository_github_id'), 'h_repository', ['github_id'], unique=True)
    op.create_index(op.f('ix_h_repository_next_scan'), 'h_repository', ['next_scan'], unique=False)
    op.create_table('h_analysis',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['h_repository.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_h_analysis_repo_id'), 'h_analysis', ['repo_id'], unique=False)
    op.create_table('h_artifact',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('revision', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['h_repository.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'path', 'revision')
    )
    op.create_index(op.f('ix_h_artifact_repo_id'), 'h_artifact', ['repo_id'], unique=False)
    op.create_table('h_candidate',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('github_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('starred_at', sa.String(), nullable=False),
    sa.Column('discovered_at', sa.Integer(), nullable=False),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['h_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'github_id', 'source')
    )
    op.create_index(op.f('ix_h_candidate_user_id'), 'h_candidate', ['user_id'], unique=False)
    op.create_table('h_delivery',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['h_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_h_delivery_user_id'), 'h_delivery', ['user_id'], unique=False)
    op.create_table('h_digest',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['h_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date')
    )
    op.create_index(op.f('ix_h_digest_user_id'), 'h_digest', ['user_id'], unique=False)
    op.create_table('h_email_verification',
    sa.Column('digest', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['h_account.id'], ),
    sa.PrimaryKeyConstraint('digest')
    )
    op.create_index(op.f('ix_h_email_verification_user_id'), 'h_email_verification', ['user_id'], unique=False)
    op.create_table('h_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['h_repository.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_h_event_created_at'), 'h_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_h_event_repo_id'), 'h_event', ['repo_id'], unique=False)
    op.create_table('h_issue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('state_reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('assignees', sa.JSON(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('analysis_hash', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('problem', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('analyzed_at', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['h_repository.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'number')
    )
    op.create_index(op.f('ix_h_issue_repo_id'), 'h_issue', ['repo_id'], unique=False)
    op.create_table('h_job',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('active_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.Integer(), nullable=False),
    sa.Column('lease_until', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['h_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_key')
    )
    op.create_index(op.f('ix_h_job_available_at'), 'h_job', ['available_at'], unique=False)
    op.create_index(op.f('ix_h_job_kind'), 'h_job', ['kind'], unique=False)
    op.create_index(op.f('ix_h_job_status'), 'h_job', ['status'], unique=False)
    op.create_index(op.f('ix_h_job_user_id'), 'h_job', ['user_id'], unique=False)
    op.create_table('h_session',
    sa.Column('digest', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('csrf', sa.String(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['h_account.id'], ),
    sa.PrimaryKeyConstraint('digest')
    )
    op.create_index(op.f('ix_h_session_expires_at'), 'h_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_h_session_user_id'), 'h_session', ['user_id'], unique=False)
    op.create_table('h_subscription',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('recipes', sa.JSON(), nullable=False),
    sa.Column('watched_issues', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['h_repository.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['h_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repo_id')
    )
    op.create_index(op.f('ix_h_subscription_repo_id'), 'h_subscription', ['repo_id'], unique=False)
    op.create_index(op.f('ix_h_subscription_user_id'), 'h_subscription', ['user_id'], unique=False)
    op.create_table('h_job_access',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['h_job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['h_account.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'user_id')
    )
    op.create_table('h_notification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('read_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['h_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['h_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id')
    )
    op.create_index(op.f('ix_h_notification_event_id'), 'h_notification', ['event_id'], unique=False)
    op.create_index(op.f('ix_h_notification_user_id'), 'h_notification', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError('Destructive downgrade disabled. Restore a verified database backup instead.')
